"""timeoff schema changes.

Revision ID: 6fa153544bf5
Revises: 0d62a0388e07
Create Date: 2025-11-21 20:16:12.256616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa153544bf5'
down_revision = '0d62a0388e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeoffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hr_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manager_decision_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('hr_decision_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['manager_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['hr_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeoffs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hr_decision_at')
        batch_op.drop_column('manager_decision_at')
        batch_op.drop_column('hr_id')
        batch_op.drop_column('manager_id')

    # ### end Alembic commands ###
